"""
è¨­è¨ˆè¦ä»¶:
    - ä¸‰ç›®ä¸¦ã¹ï¼ˆTic Tac Toeï¼‰ç”¨ã®é§’ï¼ˆã‚¤ãƒã‚´ã¨ãƒãƒ¼ã‚ºï¼‰ã‚’è¨­è¨ˆã€‚
    - ã‚¤ãƒã‚´: çœŸã®é›«å‹ï¼ˆğŸ’§ï¼‰ã‚’è¿½æ±‚ã€‚ä¸Šéƒ¨ã‚’æ»‘ã‚‰ã‹ãªå††å¼§ã€ä¸‹éƒ¨ã®ä¸€ç‚¹ã®ã¿ã‚’é‹­è§’ã«è¨­è¨ˆã€‚
    - ãƒãƒ¼ã‚º: ä¸‰è§’å½¢ã‚¦ã‚§ãƒƒã‚¸å‹ã®å˜è‰²ãƒ¢ãƒ‡ãƒ«ã€‚ç‰©ç†çš„ãªè²«é€šç©´ã‚’æŒã¤ã€‚
    - å°åˆ·æœ€é©åŒ–: ã‚¤ãƒã‚´ã¯ 0-2mm ã‚’èµ¤ã€2-4mm ã‚’ç·‘ã¨ã™ã‚‹2å±¤æ§‹é€ ï¼ˆè‰²æ›¿ãˆ1å›ï¼‰ã€‚

æ¨å¥¨ãƒ•ã‚£ãƒ©ãƒ¡ãƒ³ãƒˆ:
    - PLA (èµ¤ã€ç·‘ã€é»„)

å±¥æ­´ã¨ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆçµŒç·¯:
    - è©³ç´°ã¯åŒãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã® history.md ã‚’å‚ç…§ã€‚
"""

import cadquery as cq
import os

# --- å®šæ•°å®šç¾© ---
SIZE = 16.0
BASE_HEIGHT = 2.0
DECO_HEIGHT = 2.0
TOTAL_HEIGHT = BASE_HEIGHT + DECO_HEIGHT

# å‡ºåŠ›ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã®è¨­å®š
OUTPUT_DIR = os.path.dirname(__file__)

def create_strawberry():
    """çœŸã®é›«å‹ï¼ˆğŸ’§ï¼‰ã®ã‚¤ãƒã‚´ã‚’ä½œæˆï¼ˆé‹­è§’ã¯å…ˆç«¯ã®1ç‚¹ã®ã¿ï¼‰"""
    w = SIZE * 1.0
    h = SIZE * 1.1

    # é›«å‹ã®è¼ªéƒ­: ä¸‹ç«¯(0, -h/2)ã‚’èµ·ç‚¹ã¨ã—ã€å·¦å³ã®è‚©(w/2, h/8)ã¾ã§ç›´ç·šã€
    # ãã“ã‹ã‚‰ä¸Šç«¯(0, h/2)ã‚’çµŒç”±ã—ã¦åå¯¾ã®è‚©ã¾ã§å††å¼§ã§ã¤ãªãã€‚
    strawberry_outline = (
        cq.Workplane("XY")
        .moveTo(0, -h/2) # é‹­è§’ã¨ãªã‚‹å…ˆç«¯
        .lineTo(w/2, h/8) # ç›´ç·šã§è‚©ã¸
        .threePointArc((0, h/2), (-w/2, h/8)) # æ»‘ã‚‰ã‹ãªå††å¼§ã§é ‚ç‚¹ã‚’é€šã‚‹
        .close() # æœ€å¾Œã«ç›´ç·šã§å…ˆç«¯ã¸æˆ»ã‚‹ã“ã¨ã§è§’ãŒã§ãã‚‹
    )

    # å…¨ä½“å½¢çŠ¶ã‚’é«˜ã•ã„ã£ã±ã„ã«ä½œæˆ
    full_body = strawberry_outline.extrude(TOTAL_HEIGHT)

    # ãƒ˜ã‚¿éƒ¨åˆ†ã®å®šç¾© (2.0mm - 4.0mm)
    # å††å¼§ãªã©ã‚’ç”¨ã„ã¦æœ¬ä½“ã®æ›²ç·šã«é¦´æŸ“ã‚€ãƒ˜ã‚¿ã®å¢ƒç•Œã‚’ä½œã‚‹
    leaves_boundary = (
        cq.Workplane("XY")
        .workplane(offset=BASE_HEIGHT)
        .center(0, h/3)
        .circle(w * 0.6) # å††å½¢ã«æŠœãã“ã¨ã§å¢ƒç•Œã‚’æ»‘ã‚‰ã‹ã«
        .extrude(DECO_HEIGHT)
    )

    # ãƒ˜ã‚¿ã®å®Ÿéš›ã®å½¢çŠ¶
    leaves = (
        leaves_boundary.intersect(full_body)
    )

    # èµ¤ã„æœ¬ä½“: 0-2mm ã¯å…¨åŸŸã€2-4mm ã¯ãƒ˜ã‚¿ä»¥å¤–ã®é ˜åŸŸ
    strawberry_red = full_body.cut(leaves)
    strawberry_green = leaves

    return [
        ("strawberry_red_body", strawberry_red),
        ("strawberry_green_stem", strawberry_green)
    ]

def create_cheese():
    """ç‰©ç†çš„ãªè²«é€šç©´ã‚’æŒã¤ã‚¦ã‚§ãƒƒã‚¸å‹ã®ãƒãƒ¼ã‚ºã‚’ä½œæˆ"""
    c_size = SIZE * 1.1
    cheese_outline = (
        cq.Workplane("XY")
        .moveTo(-c_size/2, -c_size/2)
        .lineTo(c_size/2, -c_size/2)
        .lineTo(c_size/2, c_size/2)
        .close()
    )

    cheese_body = cheese_outline.extrude(TOTAL_HEIGHT)

    # ã‹ã˜ã‚Šè·¡
    bite = (
        cq.Workplane("XY")
        .center(c_size/2, 0)
        .circle(c_size*0.2)
        .extrude(TOTAL_HEIGHT)
    )

    # ç©´(è²«é€š)
    hole_positions = [
        (c_size/4, -c_size/4, c_size*0.12),
        (-c_size/8, -c_size/3, c_size*0.08),
        (c_size/2.5, c_size/4, c_size*0.07)
    ]

    holes = cq.Workplane("XY")
    for x, y, r in hole_positions:
        hole = cq.Workplane("XY").center(x, y).circle(r).extrude(TOTAL_HEIGHT)
        holes = holes.union(hole)

    cheese_final = cheese_body.cut(bite).cut(holes)

    return [
        ("cheese_yellow_single", cheese_final)
    ]

def export_step(name, pieces):
    path = os.path.normpath(os.path.join(OUTPUT_DIR, f"{name}.step"))
    assembly = cq.Assembly()
    for sub_name, part in pieces:
        assembly.add(part, name=sub_name)
    assembly.save(path, "STEP")
    print(f"Exported: {path}")

if __name__ == "__main__":
    export_step("strawberry", create_strawberry())
    export_step("cheese", create_cheese())
