"""
è¨­è¨ˆè¦ä»¶:
    - ä¸‰ç›®ä¸¦ã¹ï¼ˆTic Tac Toeï¼‰ç”¨ã®é§’ï¼ˆã‚¤ãƒã‚´ã¨ãƒãƒ¼ã‚ºï¼‰ã‚’è¨­è¨ˆã€‚
    - ç›¤é¢ 18x18mm ã«å¯¾ã—ã¦ã€é§’ã‚µã‚¤ã‚ºã‚’ ç´„16x16mmã€åšã• 4mm ã«è¨­å®šã€‚
    - ã‚¤ãƒã‚´: ãƒ™ã‚¸ã‚§æ›²ç·šã‚’ä½¿ç”¨ã—ãŸæ»‘ã‚‰ã‹ãªé›«å‹ï¼ˆğŸ’§ï¼‰+ 2å±¤æ§‹é€ ã®ãƒ˜ã‚¿ã€‚
    - ãƒãƒ¼ã‚º: ä¸‰è§’å½¢ã‚¦ã‚§ãƒƒã‚¸å‹ã®å˜è‰²ãƒ¢ãƒ‡ãƒ«ã€‚è£…é£¾ã§ã¯ãªãç‰©ç†çš„ãªã€Œç©´ï¼ˆç©ºæ´ï¼‰ã€ã‚’æŒã¤ã€‚
    - å°åˆ·æœ€é©åŒ–: ã‚¤ãƒã‚´ã¯ 0-2mm ã‚’èµ¤ã€2-4mm ã‚’ç·‘ã¨ã™ã‚‹2å±¤æ§‹é€ ã€‚

æ¨å¥¨ãƒ•ã‚£ãƒ©ãƒ¡ãƒ³ãƒˆ:
    - PLA (èµ¤ã€ç·‘ã€é»„)

å°åˆ·çµ±è¨ˆï¼ˆäºˆæƒ³ï¼‰:
    - strawberry.step: å°åˆ·æ™‚é–“ ç´„10åˆ†ï¼ˆè‰²æ›¿ãˆ1å›ï¼‰ã€ãƒ•ã‚£ãƒ©ãƒ¡ãƒ³ãƒˆä½¿ç”¨é‡ ç´„2g
    - cheese.step: å°åˆ·æ™‚é–“ ç´„5åˆ†ï¼ˆå˜è‰²ï¼‰ã€ãƒ•ã‚£ãƒ©ãƒ¡ãƒ³ãƒˆä½¿ç”¨é‡ ç´„1.5g

Bambu Studioã§ã®è¨­å®š:
    - strawberry: 2ãƒ‘ãƒ¼ãƒ„ã¨ã—ã¦ã‚¤ãƒ³ãƒãƒ¼ãƒˆã€‚ãƒ¬ã‚¤ãƒ¤ãƒ¼é«˜ã• 2.0mm ã§è‰²ã‚’åˆ‡ã‚Šæ›¿ãˆã‚‹ã€‚
    - cheese: å˜è‰²ã¨ã—ã¦ã‚¤ãƒ³ãƒãƒ¼ãƒˆã€‚

å±¥æ­´ã¨ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆçµŒç·¯:
    - è©³ç´°ã¯åŒãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã® history.md ã‚’å‚ç…§ã€‚
"""

import cadquery as cq
import os

# --- å®šæ•°å®šç¾© ---
SIZE = 16.0  # é§’ã®æœ€å¤§å¹…/é«˜ã•(mm)
BASE_HEIGHT = 2.0  # ãƒ™ãƒ¼ã‚¹éƒ¨åˆ†ã®åšã¿(mm)
DECO_HEIGHT = 2.0  # è£…é£¾éƒ¨åˆ†ã®åšã¿(mm)
TOTAL_HEIGHT = BASE_HEIGHT + DECO_HEIGHT

# å‡ºåŠ›ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã®è¨­å®š
OUTPUT_DIR = os.path.dirname(__file__)

def create_strawberry():
    """æ»‘ã‚‰ã‹ãªé›«å‹ï¼ˆğŸ’§ï¼‰ã®ã‚¤ãƒã‚´ã‚’ä½œæˆ"""
    # é›«å‹ã®è¼ªéƒ­ã‚’ãƒ™ã‚¸ã‚§æ›²ç·šã§å®šç¾©
    # ä¸‹éƒ¨ã‚’ä¸¸ãã€ä¸Šéƒ¨ã‚’ç·©ã‚„ã‹ã«çµã‚‹
    w = SIZE * 1.0
    h = SIZE * 1.1

    strawberry_outline = (
        cq.Workplane("XY")
        .moveTo(0, -h/2)
        .bezier([
            (-w/2, -h/4),
            (-w/2, h/4),
            (0, h/2),
            (w/2, h/4),
            (w/2, -h/4),
            (0, -h/2)
        ])
        .close()
    )

    # å…¨ä½“å½¢çŠ¶ã‚’é«˜ã•ã„ã£ã±ã„ã«ä½œæˆ
    full_body = strawberry_outline.extrude(TOTAL_HEIGHT)

    # ãƒ˜ã‚¿éƒ¨åˆ†ã®å®šç¾© (2.0mm - 4.0mm)
    # ä¸Šéƒ¨ã«é‡ãªã‚‹ã‚®ã‚¶ã‚®ã‚¶
    leaves_outline = (
        cq.Workplane("XY")
        .workplane(offset=BASE_HEIGHT)
        .center(0, h/4)
        .rect(w*0.8, h*0.5)
        .toPending()
    )

    # ãƒ˜ã‚¿ã®å®Ÿéš›ã®å½¢çŠ¶ï¼ˆä¸Šéƒ¨1/3ç¨‹åº¦ã‚’è¦†ã†ï¼‰
    leaves = (
        leaves_outline.extrude(DECO_HEIGHT)
        .intersect(full_body)
    )

    # èµ¤ã„æœ¬ä½“: 0-2mm ã¯å…¨åŸŸã€2-4mm ã¯ãƒ˜ã‚¿ä»¥å¤–ã®é ˜åŸŸ
    strawberry_red = full_body.cut(leaves)
    strawberry_green = leaves

    return [
        ("strawberry_red_body", strawberry_red),
        ("strawberry_green_stem", strawberry_green)
    ]

def create_cheese():
    """ç‰©ç†çš„ãªç©´ã‚’æŒã¤ã‚¦ã‚§ãƒƒã‚¸å‹ã®ãƒãƒ¼ã‚ºã‚’ä½œæˆ"""
    # ã‚¤ãƒã‚´ã¨ãƒœãƒªãƒ¥ãƒ¼ãƒ æ„Ÿã‚’åˆã‚ã›ã‚‹ãŸã‚ã‚µã‚¤ã‚ºèª¿æ•´
    c_size = SIZE * 1.1

    cheese_outline = (
        cq.Workplane("XY")
        .moveTo(-c_size/2, -c_size/2)
        .lineTo(c_size/2, -c_size/2)
        .lineTo(c_size/2, c_size/2)
        .close()
    )

    # å½¢çŠ¶ã®æŠ¼ã—å‡ºã—
    cheese_body = cheese_outline.extrude(TOTAL_HEIGHT)

    # ã‹ã˜ã‚Šè·¡
    bite = (
        cq.Workplane("XY")
        .center(c_size/2, 0)
        .circle(c_size*0.2)
        .extrude(TOTAL_HEIGHT)
    )

    # ç‰©ç†çš„ãªç©ºæ´ã¨ã—ã¦ã®ç©´
    hole_positions = [
        (c_size/4, -c_size/4, c_size*0.12),
        (-c_size/8, -c_size/3, c_size*0.08),
        (c_size/2.5, c_size/4, c_size*0.07)
    ]

    holes = cq.Workplane("XY")
    for x, y, r in hole_positions:
        hole = cq.Workplane("XY").center(x, y).circle(r).extrude(TOTAL_HEIGHT)
        holes = holes.union(hole)

    # å…¨ã¦ã®ç©ºæ´ã‚’æœ¬ä½“ã‹ã‚‰å¼•ã
    cheese_final = cheese_body.cut(bite).cut(holes)

    return [
        ("cheese_yellow_single", cheese_final)
    ]

def export_step(name, pieces):
    path = os.path.normpath(os.path.join(OUTPUT_DIR, f"{name}.step"))
    assembly = cq.Assembly()
    for sub_name, part in pieces:
        assembly.add(part, name=sub_name)
    assembly.save(path, "STEP")
    print(f"Exported: {path}")

if __name__ == "__main__":
    export_step("strawberry", create_strawberry())
    export_step("cheese", create_cheese())
