"""
è¨­è¨ˆè¦ä»¶:
    - ä¸‰ç›®ä¸¦ã¹ï¼ˆTic Tac Toeï¼‰ç”¨ã®é§’ï¼ˆã‚¤ãƒã‚´ã¨ãƒãƒ¼ã‚ºï¼‰ã‚’è¨­è¨ˆã€‚
    - ã‚¤ãƒã‚´: çœŸã®é›«å‹ï¼ˆğŸ’§ï¼‰ã‚’è¿½æ±‚ã€‚æ•°å­¦çš„ã«æ­£ç¢ºãªæ¥ç·šã‚’ç”¨ã„ã€ä¸Šéƒ¨ã‚’æ»‘ã‚‰ã‹ãªå††å¼§ã€ä¸‹éƒ¨ã®ä¸€ç‚¹ã®ã¿ã‚’é‹­è§’ã«è¨­è¨ˆã€‚
    - ãƒãƒ¼ã‚º: ä¸‰è§’å½¢ã‚¦ã‚§ãƒƒã‚¸å‹ã®å˜è‰²ãƒ¢ãƒ‡ãƒ«ã€‚ç‰©ç†çš„ãªè²«é€šç©´ï¼ˆã‹ã˜ã‚Šè·¡ã‚’å«ã‚€ï¼‰ã‚’æŒã¤ã€‚
    - å°åˆ·æœ€é©åŒ–: ã‚¤ãƒã‚´ã¯ 0-2mm ã‚’èµ¤ãƒ™ãƒ¼ã‚¹ã€2-4mm ã‚’ç·‘ã®æœ‰æ©Ÿçš„ãª5ã¤è‘‰ãƒ˜ã‚¿ã¨ã™ã‚‹2å±¤æ§‹é€ ï¼ˆè‰²æ›¿ãˆ1å›ï¼‰ã€‚

æ¨å¥¨ãƒ•ã‚£ãƒ©ãƒ¡ãƒ³ãƒˆ:
    - PLA (èµ¤ã€ç·‘ã€é»„)
    - åç¸®ã‚„åã‚Šã‚’æŠ‘ãˆã‚‹ãŸã‚ã€é€ å½¢ãƒ™ãƒƒãƒ‰ã¨ã®å¯†ç€æ€§ã«å„ªã‚ŒãŸPLAã‚’æ¨å¥¨ã€‚

å±¥æ­´ã¨ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆçµŒç·¯:
    - è©³ç´°ã¯åŒãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã® history.md ã‚’å‚ç…§ã€‚
"""

import cadquery as cq
import os
import math

# --- å®šæ•°å®šç¾© ---
SIZE = 16.0
BASE_HEIGHT = 2.0
DECO_HEIGHT = 2.0
TOTAL_HEIGHT = BASE_HEIGHT + DECO_HEIGHT

# å‡ºåŠ›ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã®è¨­å®š
OUTPUT_DIR = os.path.dirname(__file__)

def create_strawberry():
    """çœŸã®é›«å‹ï¼ˆğŸ’§ï¼‰ã®ã‚¤ãƒã‚´ã‚’ä½œæˆã€‚æ•°å­¦çš„ã«æ­£ç¢ºãªæ¥ç·šã‚’ç”¨ã„ã¦æ»‘ã‚‰ã‹ãªå½¢çŠ¶ã‚’å®Ÿç¾ã€‚"""
    w = SIZE * 1.0
    h = SIZE * 1.1

    # å®šç¾©: æœ€ä¸‹éƒ¨ã®é‹­è§’ç‚¹(0, -h/2)ã€ä¸Šéƒ¨ã®åŠå††å¼§(ä¸­å¿ƒ C=(0, y_c), åŠå¾„ R=w/2)
    R = w / 2
    y_t = -h / 2
    y_c = h / 2 - R
    d = y_c - y_t  # å…ˆç«¯ã‹ã‚‰å††ã®ä¸­å¿ƒã¾ã§ã®è·é›¢

    # æ¥ç‚¹ã®è¨ˆç®—
    sin_alpha = R / d
    cos_alpha = math.sqrt(1 - sin_alpha**2)
    px = R * cos_alpha
    py = y_c - R * sin_alpha

    # é›«å‹ã®è¼ªéƒ­: å…ˆç«¯ã‹ã‚‰ä¸¡å´ã®æ¥ç‚¹ã¾ã§ç›´ç·šã€ä¸Šéƒ¨ã¯å††å¼§ã§çµã¶
    strawberry_outline = (
        cq.Workplane("XY")
        .moveTo(0, y_t)
        .lineTo(px, py)
        .threePointArc((0, y_c + R), (-px, py))
        .close()
    )

    # å…¨ä½“å½¢çŠ¶ã‚’é«˜ã•ã„ã£ã±ã„ã«ä½œæˆ
    full_body = strawberry_outline.extrude(TOTAL_HEIGHT)

    # æœ‰æ©Ÿçš„ãª5æšã®è‘‰ã‚’æŒã¤ãƒ˜ã‚¿ã‚’ä½œæˆ
    num_leaves = 5
    R_out = w * 0.45  # è‘‰ã®å…ˆç«¯ï¼ˆå°‘ã—æ§ãˆã‚ã«ã—ã€é›«å‹ã«ã—ã£ã‹ã‚Šåã¾ã‚‹ã‚ˆã†ã«ï¼‰
    R_in = w * 0.15   # è‘‰ã®æ ¹æœ¬
    cx, cy = 0, y_c + R * 0.3  # ä¸Šéƒ¨ã®å††ã®ä¸­å¿ƒã‚ˆã‚Šå°‘ã—ä¸Šã«é…ç½®

    leaf_pts = []
    for i in range(num_leaves * 2):
        # æœ€åˆã®è‘‰ãŒä¸Š(Yè»¸æ­£æ–¹å‘)ã‚’å‘ãã‚ˆã†ã«è§’åº¦ã‚’è¨­å®š
        angle = math.pi / 2 + i * math.pi / num_leaves
        r_current = R_out if i % 2 == 0 else R_in
        leaf_pts.append((cx + r_current * math.cos(angle), cy + r_current * math.sin(angle)))

    leaves_boundary = (
        cq.Workplane("XY")
        .workplane(offset=BASE_HEIGHT)
        .polyline(leaf_pts).close()
        .extrude(DECO_HEIGHT)
    )

    # ãƒ˜ã‚¿ã®å®Ÿéš›ã®å½¢çŠ¶ï¼ˆé›«å‹ã®å¤–å´ã«ã¯ã¿å‡ºã•ãªã„ã‚ˆã†äº¤å·®ã‚’ã¨ã‚‹ï¼‰
    leaves = leaves_boundary.intersect(full_body)

    # èµ¤ã„æœ¬ä½“: 0-2mmã¯å…¨åŸŸã€2-4mmã¯ãƒ˜ã‚¿ä»¥å¤–ã®é ˜åŸŸ
    strawberry_red = full_body.cut(leaves)
    strawberry_green = leaves

    return [
        ("strawberry_red_body", strawberry_red),
        ("strawberry_green_stem", strawberry_green)
    ]

def create_cheese():
    """ç‰©ç†çš„ãªè²«é€šç©´ï¼ˆã‹ã˜ã‚Šè·¡ã‚’å«ã‚€ï¼‰ã‚’æŒã¤ã‚¦ã‚§ãƒƒã‚¸å‹ã®ãƒãƒ¼ã‚ºã‚’ä½œæˆ"""
    c_size = SIZE * 1.1

    # ä¸‰è§’å½¢ã‚¦ã‚§ãƒƒã‚¸ã®è¼ªéƒ­
    cheese_outline = (
        cq.Workplane("XY")
        .moveTo(-c_size/2, -c_size/2)
        .lineTo(c_size/2, -c_size/2)
        .lineTo(c_size/2, c_size/2)
        .close()
    )

    cheese_body = cheese_outline.extrude(TOTAL_HEIGHT)

    # ã‹ã˜ã‚Šè·¡
    bite = (
        cq.Workplane("XY")
        .center(c_size/2, 0)
        .circle(c_size*0.2)
        .extrude(TOTAL_HEIGHT)
    )

    cheese_final = cheese_body.cut(bite)

    # ãƒ©ãƒ³ãƒ€ãƒ ãªå¤§å°ã®è²«é€šç©´
    hole_positions = [
        (c_size/4, -c_size/4, c_size*0.12),
        (-c_size/8, -c_size/3, c_size*0.08),
        (c_size/2.5, c_size/4, c_size*0.07)
    ]

    for x, y, r in hole_positions:
        hole = cq.Workplane("XY").center(x, y).circle(r).extrude(TOTAL_HEIGHT)
        cheese_final = cheese_final.cut(hole)

    return [
        ("cheese_yellow_single", cheese_final)
    ]

def export_step(name, pieces):
    path = os.path.normpath(os.path.join(OUTPUT_DIR, f"{name}.step"))
    assembly = cq.Assembly()
    for sub_name, part in pieces:
        assembly.add(part, name=sub_name)
    assembly.save(path, "STEP")
    print(f"Exported: {path}")

if __name__ == "__main__":
    export_step("strawberry", create_strawberry())
    export_step("cheese", create_cheese())
